name: backend CI Workflow

on:
  pull_request:
    branches:
      - main
    paths:
    - 'starter/backend/**'
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run the workflow on'
        required: true
        default: 'main'
        type: string

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
           python-version: '3.10'

      - name: Install pipenv
        run: |
          cd starter/backend  
          pip install pipenv
      
      - name: Install dependencies
        run: |
          cd starter/backend
          pipenv install --dev

      - name: Run lint
        run: |
          cd starter/backend
          pipenv run lint

  test:
    runs-on: ubuntu-latest
    needs: lint  # Ensures that the test job waits for the lint job to complete
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
           python-version: '3.10'

      - name: Install pipenv
        run: |
          cd starter/backend  
          pip install pipenv

      - name: Install dependencies
        run: |
          cd starter/backend 
          pipenv install

      - name: Run tests
        run: |
          cd starter/backend 
          pipenv run test

  build:
    runs-on: ubuntu-latest
    needs: [lint, test]  # Ensures the build job waits for both lint and test jobs to complete
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build docker image
        run: |
          cd starter/backend 
          docker build --tag mp-backend:latest .
      
      - name: Run docker image
        run: |
          docker run -p 5000:5000 --name mp-backend -d mp-backend
          curl http://localhost:5000/movies
          docker logs -f mp-backend
          docker stop